const SET_RESULT_VARIABLE_TYPE_EVENT = 'tokenSimulation.resultVariableType.set';
const GET_RESULT_VARIABLE_TYPE_EVENT = 'tokenSimulation.resultVariableType.get';
const CODE_EDITOR_PLUGIN_PRESENT_EVENT = 'codeEditor.init';
const RUN_CODE_EVALUATION_EVENT = 'codeEditor.run';
const GET_DATA_TYPES_EVENT = 'codeEditor.getTypes';

const LOW_PRIORITY = 500;
const DEFAULT_PRIORITY = 1000;
const MID_HIGH_PRIORITY = 6000;
const HIGH_PRIORITY = 10000;

export {
  SET_RESULT_VARIABLE_TYPE_EVENT,
  GET_RESULT_VARIABLE_TYPE_EVENT,
  CODE_EDITOR_PLUGIN_PRESENT_EVENT,
  RUN_CODE_EVALUATION_EVENT,
  GET_DATA_TYPES_EVENT,

  LOW_PRIORITY,
  DEFAULT_PRIORITY,
  MID_HIGH_PRIORITY,
  HIGH_PRIORITY
}